# Site settings
title: Webworkers Blog
subtitle: Nils Bolsen & André Borges
email: nils@bolsen.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webworkers.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  webwb
paginate: 5
# Build settings
markdown: kramdown
exclude: [".c9"]
author1: andre
# prose
prose:
  rooturl: ''
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "select"
          label: "Who are you ?"
          placeholder: "Choose your name"
          options:
            - name: "Andre"
              value: "André Borges"
            - name: "Nils"
              value: "Nils Bolsen"
      - name: "published"
        field:
          element: "select"
          label: "Publish or Draft?"
          options:
            - name: "Publish"
              value: "true"
            - name: "Draft"
              value: "false"


