# Site settings
title: Webworkers Blog
subtitle: Nils Bolsen & André Borges
email: nils@bolsen.de
description: > # this means to ignore newlines until "baseurl:"
  We write about digital things & things we like.
  This is a blog from webworkers for everyone who loves the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webworkers.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  webwb
paginate: 5
# Build settings
markdown: kramdown
exclude: [".c9"]
author1: andre
# prose
prose:
  rooturl: '_posts'
  # siteurl: 'http://webworkers.io/'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
