# Site settings
title: Webworkers Blog
subtitle: Nils Bolsen & André Borges
email: nils@bolsen.de
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://webworkers.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  webwb
paginate: 5
# Build settings
markdown: kramdown
exclude: [".c9"]
author1: andre
# prose
prose:
  rooturl: '_posts'
  # siteurl: 'http://webworkers.io/'
  media: 'images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "author"
        field:
          element: "select"
          label: "Autor"
          placeholder: "Choose your name"
          options:
            - name: "Andre"
              value: "André Borges"
            - name: "Nils"
              value: "Nils Bolsen"
      - name: "title"
        field:
          element: "text"
          label: "Titel des Posts"
          type: "text"
      - name: "published"
        field:
          element: 'hidden'
          value: true
      - name: "comments"
        field:
          element: "checkbox"
          label: "Kommentare"
          value: true
      - name: "categories"
        field:
          element: "select"
          label: "Kategorie"
          options:
            - name: "Real Life"
              value: "life"
            - name: "Digital Life"
              value: "digital"
            - name: "Online Life"
              value: "online"
            - name: "Book"
              value: "book"
      - name: "image"
        field:
          element: "text"
          label: "Teaser Bild"
          type: "text"
          help: "Das Bild muss vorher hochgeladen sein."


